In [ ]:
import numpy as np
arr=np.array([1,2,3])
arr

array([1, 2, 3])

Perfect 😎🔥 now we switch to NumPy practice mode.

Since you already know basics, I’ll give you progressive exercises (easy → advanced) like SQL style.

🧪 NUMPY PRACTICE SET (NP1–NP20)

👉 You solve → I review like interviewer 💪

🟢 LEVEL 1 – Basics (Foundation)
NP1

Create a NumPy array from list [10, 20, 30, 40]

NP2

Create a 1D array of numbers from 1 to 20

NP3

Create a 3×3 matrix filled with zeros

NP4

Create a 4×4 matrix filled with ones

NP5

Create an array of even numbers from 2 to 50

🟡 LEVEL 2 – Indexing & Slicing
NP6

From array [10,20,30,40,50], extract:

First 3 elements
Last 2 elements
NP7

Create a 5×5 matrix and:

Extract 2nd row
Extract 3rd column
NP8

Reverse an array

NP9

Replace all even numbers in an array with 0

NP10

Extract elements greater than 25

🔵 LEVEL 3 – Operations
NP11

Create two arrays and perform:

Addition
Subtraction
Multiplication
NP12

Find:

Mean
Median
Standard deviation
NP13

Find max and min values in array

NP14

Find index of maximum value

NP15

Reshape array of size 12 into 3×4

🔴 LEVEL 4 – Advanced (Interview Level)
NP16

Create random array of size 10 and sort it

NP17

Normalize an array (0–1 scaling)

NP18

Find unique elements in array

NP19

Stack two arrays vertically and horizontally

NP20

Create a 5×5 identity matrix

🔥 BONUS (Real Data Thinking)
NP21

Given array:

[10, 20, 30, 40, 50]

Convert to:

[0, 10, 20, 30, 40]

(shift right)

NP22

Find duplicates in array

NP23

Count frequency of elements

🎯 How We Proceed

Start with:

👉 NP1 to NP5 (quick warm-up)

Then jump to:
👉 NP9, NP12, NP17 (important)

Then:
👉 NP20+ (real-world thinking)



In [ ]:
arr=np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [ ]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr=np.zeros([3,3],dtype=int)
arr


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr=np.ones([4,4],dtype=int)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
#Create an array of even numbers from 2 to 50
arr=np.arange(2,51,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])